print("Please enter the following information so I can sell it for a profit!")
print()

first_name = input("First name: ")
last_name = input("Last name: ")
grade = int(input("Grade (9-12): "))
student_id = int(input("Student ID: "))
login = input("Login: ")
average = float(input("Average: "))

print()
print("Your information:")
print(f"    Login:     {login}")
print(f"    ID:        {student_id}")
print(f"    Name:      {last_name}, {first_name}")
print(f"    Average:   {average} %")
print(f"    Grade:     {grade}")
